name = "OceanSonar"
uuid = "03019ade-4524-4ecd-af79-46d4f04a1b56"
authors = ["Aaron Kaw <aaronjkaw@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
OceanSonarMakieExt = "Makie"

[compat]
AbstractTrees = "0.4"
InteractiveUtils = "1.11"
IntervalArithmetic = "0.22.14"
Makie = "0.21"
ModelingToolkit = "9.30"
OrdinaryDiffEq = "6.87"
julia = "1.10"
