name = "OceanSonar"
uuid = "03019ade-4524-4ecd-af79-46d4f04a1b56"
authors = ["Aaron Kaw <aaronjkaw@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
AbstractTrees = "0.4"
InteractiveUtils = "1.11.0"
ModelingToolkit = "9.30.0"
OrdinaryDiffEq = "6.87.0"
julia = "1.10"
