name = "OceanSonar"
uuid = "03019ade-4524-4ecd-af79-46d4f04a1b56"
authors = ["Aaron Kaw <aaronjkaw@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
DataInterpolations = "6.2.0"
ForwardDiff = "0.10.36"
OrdinaryDiffEq = "6.87.0"
julia = "1.11"
