name = "OceanSonar"
uuid = "03019ade-4524-4ecd-af79-46d4f04a1b56"
authors = ["Aaron Kaw <aaronjkaw@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
InteractiveUtils = "1.11.0"
julia = "1.11.0"
