name = "OceanSonar"
uuid = "606d67fd-65b6-4abb-b2f0-1946d248e4dc"
authors = ["Aaron Kaw <aaronjkaw@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
OceanSonarMakieExt = "Makie"
OceanSonarPlotsExt = "Plots"

[compat]
ForwardDiff = "0.10"
Interpolations = "0.15"
IntervalArithmetic = "0.22"
LinearAlgebra = "1.10"
Makie = "0.21"
NaNMath = "1.0"
OrdinaryDiffEq = "6.85"
Plots = "1.40"
PrecompileTools = "1.2"
Statistics = "1.10"
julia = "1.11"
